"""
UI theme constants for PDF Merger application.
Clean enterprise internal tool - flat dark theme, no gradients.
"""

# Layout (px)
CORNER_RADIUS = 12
INPUT_RADIUS = 8
CARD_PADDING = 20
SECTION_SPACING = 32
CARD_SPACING = 16
SUMMARY_CARD_SPACING = 16
LABEL_INPUT_SPACING = 12
CONTENT_MAX_WIDTH = 1000
METRIC_CARD_PADDING = 16

# Colors (flat dark theme - spec)
APP_BACKGROUND = "#121212"
CARD_BACKGROUND = "#1E1E1E"
CARD_BORDER = "#2A2A2A"
INPUT_BACKGROUND = "#262626"
PRIMARY_BLUE = "#2B8BE6"
PRIMARY_BLUE_HOVER = "#3B9BF6"
SUCCESS_GREEN = "#22C55E"
WARNING_YELLOW = "#FACC15"
ERROR_RED = "#EF4444"
TEXT_PRIMARY = "#E5E7EB"
TEXT_SECONDARY = "#9CA3AF"

# Aliases for backward compatibility (preferred names: CARD_BACKGROUND, ERROR_RED, etc.)
BG_DARK = APP_BACKGROUND
CARD_BG = CARD_BACKGROUND
INPUT_CONTAINER_BG = INPUT_BACKGROUND
INPUT_BG = INPUT_BACKGROUND
LOG_BG = "#1A1A1A"
FOCUS_BLUE = PRIMARY_BLUE
INPUT_HOVER_BG = "#2E2E2E"
GREEN_SUCCESS = SUCCESS_GREEN
RED_ERROR = ERROR_RED
YELLOW_WARNING = WARNING_YELLOW
BLUE_INFO = TEXT_SECONDARY

# Results mini-card
METRIC_CARD_BG = "#242424"

# Step symbols for setup cards (Instructions File, Source Directory, Output Directory)
STEP_SYMBOLS = ("①", "②", "③")

# Typography
FONT_TITLE_SIZE = 28
FONT_SECTION_SIZE = 18
FONT_LABEL_SIZE = 14
FONT_HELPER_SIZE = 12
FONT_MONO_SIZE = 12
FONT_METRIC = 30
FONT_SUMMARY_NUMBER = FONT_METRIC
